#ifndef UNI_ENUMQUALIDADEESCALA_H
#define UNI_ENUMQUALIDADEESCALA_H

#include "uniAPI.h"

enum UNI_API EnumQualidadeEscala
{
	QUALIDADE_ESCALA_BAIXA,
	QUALIDADE_ESCALA_MEDIA,
	QUALIDADE_ESCALA_ALTA
};

#endif
